#!/usr/bin/env bash
# SAC Smart Charging – Streamlit operations dashboard – service manager
# Usage: ./dashboard.sh {start|stop|restart|status|logs}
#
# Runs as its own process next to serve.py and reads it over HTTP, so the
# inference server must be running (or SERVE_URL must point at one).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PID_FILE="$ROOT_DIR/.dashboard.pid"
LOG_FILE="$ROOT_DIR/dashboard.log"

HOST="${DASHBOARD_HOST:-0.0.0.0}"
PORT="${DASHBOARD_PORT:-8501}"
export SERVE_URL="${SERVE_URL:-http://127.0.0.1:${SERVE_PORT:-8000}}"

# Keycloak (same realm as the operator tools). Values come from Infisical:
# citrineos project, prod environment, this service's own /ml folder.
INFISICAL_PROJECT="${INFISICAL_PROJECT:-citrineos}"
INFISICAL_PROJECT_ID="${INFISICAL_PROJECT_ID:-98538adb-d5d9-46f6-9920-8f66af3122f0}"
INFISICAL_ENV="${INFISICAL_ENV:-prod}"
INFISICAL_PATH="${INFISICAL_PATH:-/ml}"
KEYCLOAK_URL="${KEYCLOAK_URL:-https://login.ai-charge.net}"
KEYCLOAK_REALM="${KEYCLOAK_REALM:-AI-Charge-Technologies}"
SECRETS_FILE="$ROOT_DIR/.streamlit/secrets.toml"

# Resolves a setting from the environment, else from Infisical via config.py.
_cfg() {
    local v="${!1:-}"
    if [[ -z "$v" && -n "${INFISICAL_CLIENT_ID:-}" ]]; then
        v=$(python "$ROOT_DIR/config.py" "$1" 2>/dev/null) || true
    fi
    printf '%s' "$v"
}

_activate() {
    # shellcheck source=/dev/null
    source "$ROOT_DIR/.venv/bin/activate"
}

_is_running() {
    [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null
}

# Writes .streamlit/secrets.toml (git-ignored, mode 600) so Streamlit's
# native OIDC can talk to Keycloak. Credentials are read from Infisical
# when available, otherwise from the environment. Nothing is committed.
_write_secrets() {
    if [[ "${DASHBOARD_ALLOW_ANONYMOUS:-}" == "1" ]]; then
        echo "WARNING: DASHBOARD_ALLOW_ANONYMOUS=1 — starting without authentication."
        return 0
    fi

    local cid="${KEYCLOAK_CLIENT_ID:-}" csec="${KEYCLOAK_CLIENT_SECRET:-}"

    if [[ -z "$cid" || -z "$csec" ]] && [[ -n "${INFISICAL_CLIENT_ID:-}" ]]; then
        echo "Reading Keycloak credentials from Infisical ($INFISICAL_PROJECT $INFISICAL_ENV:$INFISICAL_PATH) ..."
        # config.py speaks to Infisical directly, so the host needs no CLI and
        # the server and the dashboard resolve configuration the same way.
        mapfile -t _kc < <(python "$ROOT_DIR/config.py" KEYCLOAK_CLIENT_ID KEYCLOAK_CLIENT_SECRET) || true
        cid="${_kc[0]:-}"
        csec="${_kc[1]:-}"
    fi

    if [[ -z "$cid" || -z "$csec" ]]; then
        echo "ERROR: no Keycloak credentials." >&2
        echo "  Set KEYCLOAK_CLIENT_ID / KEYCLOAK_CLIENT_SECRET, or provide" >&2
        echo "  INFISICAL_ENDPOINT / INFISICAL_CLIENT_ID / INFISICAL_CLIENT_SECRET" >&2
        echo "  (INFISICAL_PROJECT_ID / _ENV / _PATH default to citrineos prod:/ml)." >&2
        echo "  For local development only: DASHBOARD_ALLOW_ANONYMOUS=1" >&2
        exit 1
    fi

    # Streamlit signs its auth cookie with this; keep it stable across restarts
    # so a running session survives a service restart.
    local cookie_secret_file="$ROOT_DIR/.streamlit/.cookie_secret"
    mkdir -p "$ROOT_DIR/.streamlit"
    chmod 700 "$ROOT_DIR/.streamlit"
    if [[ ! -s "$cookie_secret_file" ]]; then
        head -c 48 /dev/urandom | base64 | tr -d '\n' > "$cookie_secret_file"
        chmod 600 "$cookie_secret_file"
    fi

    umask 077
    cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/dashboard.sh — do not commit, do not edit by hand.
[auth]
redirect_uri = "${PUBLIC_URL}/oauth2callback"
cookie_secret = "$(cat "$cookie_secret_file")"

[auth.keycloak]
client_id = "${cid}"
client_secret = "${csec}"
server_metadata_url = "${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"
EOF
    chmod 600 "$SECRETS_FILE"
    echo "Wrote $SECRETS_FILE (redirect_uri ${PUBLIC_URL}/oauth2callback)"
}

cmd_start() {
    if _is_running; then
        echo "Already running (PID $(cat "$PID_FILE"))."
        return 0
    fi
    if ss -tlnp 2>/dev/null | grep -q ":${PORT} " || \
       netstat -tlnp 2>/dev/null | grep -q ":${PORT} "; then
        echo "ERROR: Port $PORT is already in use."
        exit 1
    fi
    _activate
    PUBLIC_URL="$(_cfg DASHBOARD_PUBLIC_URL)"
    PUBLIC_URL="${PUBLIC_URL:-http://${HOST}:${PORT}}"
    _write_secrets
    echo "[$(date '+%F %T')] Starting dashboard on http://$HOST:$PORT (API: $SERVE_URL) ..." | tee -a "$LOG_FILE"
    nohup streamlit run "$ROOT_DIR/dashboard_app.py" \
        --server.address "$HOST" \
        --server.port "$PORT" \
        --server.headless true \
        --client.toolbarMode minimal \
        --browser.gatherUsageStats false \
        >> "$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    sleep 2
    if _is_running; then
        echo "Started (PID $(cat "$PID_FILE"))."
        echo "  Logs : $LOG_FILE"
        echo "  UI   : $PUBLIC_URL"
        echo "  API  : $SERVE_URL/api/dashboard"
        if [[ "${DASHBOARD_ALLOW_ANONYMOUS:-}" == "1" ]]; then
            echo "  Auth : DISABLED (local development only)"
        else
            echo "  Auth : Keycloak realm $KEYCLOAK_REALM at $KEYCLOAK_URL"
        fi
    else
        echo "ERROR: Dashboard failed to start. Check $LOG_FILE"
        rm -f "$PID_FILE"
        exit 1
    fi
}

cmd_stop() {
    if ! _is_running; then
        echo "Not running."
        rm -f "$PID_FILE"
        return 0
    fi
    PID=$(cat "$PID_FILE")
    echo "Stopping PID $PID ..."
    kill "$PID"
    for _ in $(seq 10); do
        _is_running || break
        sleep 1
    done
    if _is_running; then
        echo "Force-killing PID $PID ..."
        kill -9 "$PID" 2>/dev/null || true
    fi
    rm -f "$PID_FILE"
    echo "Stopped."
}

cmd_status() {
    if _is_running; then
        echo "Running (PID $(cat "$PID_FILE")) on http://$HOST:$PORT → $SERVE_URL"
    else
        echo "Not running."
    fi
}

cmd_logs() {
    if [[ ! -f "$LOG_FILE" ]]; then
        echo "No log file at $LOG_FILE"
        return 1
    fi
    tail -f "$LOG_FILE"
}

CMD="${1:-start}"
case "$CMD" in
    start)   cmd_start   ;;
    stop)    cmd_stop    ;;
    restart) cmd_stop; cmd_start ;;
    status)  cmd_status  ;;
    logs)    cmd_logs    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|logs}"
        exit 1
        ;;
esac
